services:
  messenger:
    build: 
      context: .
    depends_on:
      - mysql-db
    networks:
      - laravel_network

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
